vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=2")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.g.mapleader = " "
vim.keymap.set("n", "<Leader>w", "<C-w>", {})
vim.keymap.set("n", "<C-Left>", ":vertical resize -2<CR>", {})
vim.keymap.set("n", "<C-Right>", ":vertical resize +2<CR>", {})
vim.keymap.set("n", "<C-Up>", ":resize -2<CR>", {}) vim.keymap.set("n", "<C-Down>", ":resize +2<CR>", {}) vim.keymap.set({ "v", "n" }, "<Leader>j", ":bprev<CR>", {}) vim.keymap.set({ "v", "n" }, "<Leader>k", ":bnext<CR>", {})
vim.keymap.set({ "v", "n" }, "<Leader>dd", ":bd<CR>", {})
